- name: Instalar Apache en RedHat/CentOS
  hosts: all
  become: true

  tasks:
    - name: Instalar Apache (httpd)
      yum:
        name: httpd
        state: present

    - name: Habilitar y arrancar servicio httpd
      service:
        name: httpd
        state: started
        enabled: true
