---
ansible_user: ansible
ansible_password: Ansible12
ansible_port: 5985
ansible_connection: winrm
ansible_winrm_scheme: http
ansible_winrm_transport: basic
ansible_winrm_server_cert_validation: ignore
