---
- name: Wait for master to be ready
  wait_for:
    host: "{{ groups['master'][0] }}"
    port: 6443
    delay: 10
    timeout: 300

- name: Check if kubeadm join command file exists
  stat:
    path: /tmp/kubernetes_join_command
  register: join_command_file

- name: Join worker to cluster
  shell: "cat /tmp/kubernetes_join_command | sed '1d;$d' | sh"
  args:
    creates: /etc/kubernetes/kubelet.conf
  when: join_command_file.stat.exists
